apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: al31bo0no-nodejs-gitops
  description: This is GitOps manifest for al31bo0no-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=al31bo0no-nodejs
    backstage.io/kubernetes-id: al31bo0no-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: al31bo0no-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:al31bo0no-nodejs
