apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: al31bo0no-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: al31bo0no-nodejs 
  name: al31bo0no-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: al31bo0no-nodejs 
